{
 "title": "Metrics for Everyuser",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "Username",
    "query": "{\"find\": \"terms\", \"field\":  \"username\", \"query\": \"username:*\"}"
   },
   {
    "name": "editor",
    "label": "Editor",
    "query": "{\"find\": \"terms\", \"field\":  \"editor\", \"query\": \"editor:*\"}"
   },
   {
    "name": "model_completions",
    "label": "Model Completions",
    "query": "{\"find\": \"terms\", \"field\":  \"model\", \"query\": \"model:*\"}"
   },
   {
    "name": "model_chat",
    "label": "Model Chat",
    "query": "{\"find\": \"terms\", \"field\":  \"model\", \"query\": \"model:*\"}"
   },
   {
    "name": "model_extension",
    "label": "Model Extension",
    "query": "{\"find\": \"terms\", \"field\":  \"model\", \"query\": \"model:*\"}"
   },
   {
    "name": "language",
    "label": "Language",
    "query": "{\"find\": \"terms\", \"field\":  \"language\", \"query\": \"language:*\"}"
   },
   {
    "name": "chat_type",
    "label": "Chat Type",
    "query": "{\"find\": \"terms\", \"field\":  \"chat_type\", \"query\": \"chat_type:*\"}"
   },
   {
    "name": "extension",
    "label": "Extension",
    "query": "{\"find\": \"terms\", \"field\":  \"extension\", \"query\": \"extension:*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "For 📖tutorials & 💖feedback, please visit the repo \"Copilot Metrics for Every User\", Click👉",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Completions Count  by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_completions AND language: $language",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Completions Count by Editor",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "editor",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_completions AND language: $language",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Completions Count by Model",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "model",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_completions AND language: $language",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Completions Count by Language",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "language",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_completions AND language: $language",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Total Completions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_completions AND language: $language",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Completions Count by Day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_completions AND language: $language",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Chat Count  by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_chat AND chat_type: $chat_type",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Chat Count by Editor",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "editor",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_chat AND chat_type: $chat_type",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Chat Count by Model",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "model",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_chat AND chat_type: $chat_type",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Chat Count by Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "chat_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_chat AND chat_type: $chat_type",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Total Chat Turns",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_chat AND chat_type: $chat_type",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Chat Count by Day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_chat AND chat_type: $chat_type",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Extension Count by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_extension AND extension: $extension",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Extension Count by Editor",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "editor",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_extension AND extension: $extension",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Extension Count by Model",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "model",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_extension AND extension: $extension",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Extension Count by Name",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "extension",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_extension AND extension: $extension",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Total Extension ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_extension AND extension: $extension",
     "timeField": "day"
    }
   ]
  },
  {
   "title": "Extension Count by Day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "day", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "username: $username AND editor: $editor AND model: $model_extension AND extension: $extension",
     "timeField": "day"
    }
   ]
  }
 ]
}